### ISSUE TITLE
Want a function to send audio

### ISSUE THREAD

**Issue by gnjbm1px263cywt7** [eric2788/koishi-plugin-random-source-selector#1]
Want a function to send audio

**Comment by eric2788** [comment]
你的鏈接返回頁面是直接一條音頻嗎，還是json裡面有一條音頻url

**Comment by gnjbm1px263cywt7** [comment]
The url in the returned json

**Comment by eric2788** [comment]
了解，這幾天內會加

另外如果你返回的是json數據，這邊有一個臨時的解決方法:

- 數據返回類型選擇 ``源數據``
- 發送類型選擇 ``EJS模版``
架設你的json數據如下:
```json
{
    "audio": "https://abc.xyz/audio.mp3"
}
```
則輸入如下的ejs
```ejs
<audio url="<%= data.audio %>"></audio>
```

**Comment by eric2788** [comment]
新版本已出，你试试看有没有问题

**Comment by gnjbm1px263cywt7** [comment]
> 新版本已出，你试试看有没有问题

Used it well, no problems
