### ISSUE TITLE
enhancement: Instruction parameter function

### ISSUE THREAD

**Issue by gnjbm1px263cywt7** [eric2788/koishi-plugin-random-source-selector#2]
Gets the parameter after the instruction and uses it as the value of the request parameter

**Comment by eric2788** [comment]
Currently it does have query parameter customizable with your command arguments.

```html
https://google.com/search?q={0}
```

```bash
google cat
```

will output

```html
https://google.com/search?q=cat
```

**Comment by gnjbm1px263cywt7** [comment]
It really exists
